spring:
  datasource:
    url: jdbc:mysql://dabaseshopticket.mysql.database.azure.com:3306/shopticket?useSSL=true
    username: martina
    password: Casola7.
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.MySQLInnoDBDialect


server:
  port: 8080

keycloak:
  realm: ShopTicket
  resource: spring-boot-shopticket
  auth-server-url: https://kcshopticket.azurewebsites.net/auth
  ssl-required: external
  public-client: true
  principal-attribute: preferred_username
